/*Q2.What is the Crime of a particular person ?*/
SELECT CASE_TYPE FROM
COMPLAINT AS C, CRIME AS CR 
WHERE CR.COMPLAINT_NO=C.COMPLAINT_NO AND CR.COMPLAINT_NO=12345678;
/*Q3.When Was the particular Crime took place and where ?*/
SELECT DATE,TIME,PLACE
FROM COMPLAINT AS C , CRIME AS CR 
WHERE CR.COMPLAINT_NO=C.COMPLAINT_NO AND CR.COMPLAINT_NO=12345677;
/*Q4.Who is the policeman handling the particular case ?*/
SELECT OF.NAME,OFF_NO 
FROM COMPLAINT AS C , OFFICER AS OF
WHERE C.COMPLAINT_NO=OF.COMPLAINT_NO AND C.COMPLAINT_NO=12345675;
/*Q5.What is the outcome of the particular case ?*/
SELECT * 
FROM COMPLAINT AS C ,OUTCOME AS OUT
WHERE OUT.COMPLAINT_NO=C.COMPLAINT_NO AND OUT.COMPLAINT_NO=12345678;
/*Q6.What Is the Evidence of the case ?*/
SELECT * 
 FROM COMPLAINT AS C ,EVIDENCE AS E
 WHERE C.COMPLAINT_NO=E.ID AND E.ID=12345678;
/*Q7.When did the Investigation start ?*/
SELECT COMPLAINT_NUMBER,DATE_OF_START 
 FROM COMPLAINT AS C , INVESTIGATION AS I 
 WHERE I.COMPLAINT_NUMBER=C.COMPLAINT_NO;
/*Q8.What Is the FIR_NO of the particular complaint ?*/
SELECT F.COMPLAINT_NO,FIR_NO 
 FROM COMPLAINT AS C , FIR AS F 
 WHERE C.COMPLAINT_NO=F.COMPLAINT_NO AND C.COMPLAINT_NO=12345678;
 
 





	 
